spring:
  cloud:
    gateway:
      routes:

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              -GET
              -POST
            allowedHeaders: "*"
  application:
    name: Apigateway
