spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_HOST}
          predicates:
            - Path=/auth/**
        - id: code-service
          uri: ${CODES_SERVICE_HOST}
          predicates:
            - Path=/code/**
        - id: click-service
          uri: ${CLICKS_SERVICE_HOST}
          predicates:
            - Path=/click/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  application:
    name: Apigateway
  auth:
    service:
      uri: ${AUTH_SERVICE_HOST}
  config:
    import: optional:file:.env[.properties]
server:
  port: 8080