spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: code-service
          uri: http://localhost:8082
          predicates:
            - Path=/code/**
        - id: click-service
          uri: http://localhost:8083
          predicates:
            - Path=/click/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  application:
    name: Apigateway
server:
  port: 8080